/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is checked in here so
// the scaffold is type-checkable immediately after dependencies are installed.
